version: "3.9"
services:
  daemon:
    build:
      context: ./../../
      dockerfile: ./packages/composedb/daemon/Dockerfile
    ports:
      - "7007:7007"

  server:
    build:
      context: ./../../
      dockerfile: ./packages/composedb/server/Dockerfile
    ports:
      - "7008:7008"
    extra_hosts:
      - "host.docker.internal:host-gateway"

